controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    use_sim_time: true

    arm_position_controller:
      type: position_controllers/JointGroupPositionController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_position_controller:
  ros__parameters:
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - link5__link6
      - finger_right_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity